launchdarkly/js-core

- packages/sdk/cloudflare/README.md
- packages/sdk/cloudflare/src/createLDClient/CloudflareImpl.ts
- packages/sdk/cloudflare/src/createLDClient/createOptions.ts
- packages/sdk/cloudflare/src/createLDClient/index.ts
- packages/sdk/cloudflare/src/index.test.ts
- packages/sdk/cloudflare/src/index.ts
- packages/sdk/cloudflare/src/utils/mockKV.ts
Typedoc does not play nice 100% so this is best-effort.
> feat: fix typedoc and export common types

- contributing/initial-package-publish.md
Add some documentation explaining steps for doing an initial package release. These need done once, and subsequent releases should not require them.
> chore: Document initial release process.

- scripts/publish-doc.sh
When releasing multiple packages the documentation can change during the publish. This tries to mitigate possible issues by pulling before pushing.
> build: Make docs publish more robust.

- packages/sdk/cloudflare/README.md
- packages/shared/sdk-server/package.json
Semver [v7.5.0](https://github.com/npm/node-semver/compare/v7.4.0...v7.5.0#diff-7917f8ef42ff71df5bde71c259d15feab8b147e3e6c2fde11b56cbf42cadea16R19) adds a version check on the node util class with a `require('util')` statement which breaks nodejs compatibility in a worker environment. This should have been `require('node:util')`. The workaround is for our customers to use a bundler for the application, but that's not very nice.
So this ticket we'll freeze the semver package version to 7.4.0 which does not have `require('util')` statement.
> fix: semver util import error

- packages/shared/sdk-server/package.json
- release-please-config.json
Remove release-as and sha from cloudflare and sdk-server-edge packages now that they are published.
> chore: remove release-as and sha

- packages/shared/sdk-server-edge/src/api/createOptions.ts
The options below are already defined with the same defaults in the common sdk-server [Configuration](https://github.com/launchdarkly/js-core/blob/6be132f19284a65bf0623e51b9d3ae047f89a879/packages/shared/sdk-server/src/options/Configuration.ts#L64) class so we can safely remove them for the edge sdk to avoid repetition:
```js
stream: false,
sendEvents: false,
// offline: false,
useLdd: true,
// allAttributesPrivate: false,
// privateAttributes: [],
// contextKeysCapacity: 1000,
// contextKeysFlushInterval: 300,
diagnosticOptOut: true,
// diagnosticRecordingInterval: 900,
logger: BasicLogger.get(),
```
> fix: remove useless defaults

- packages/sdk/vercel/src/createPlatformInfo.test.ts
- packages/sdk/vercel/src/createPlatformInfo.ts
I was getting build errors complaining about package.json only being able to be used as a default import/export in ESM
> fix: fix packagejson import

- release-please-config.json
Forgot that we had to hardcode the version and commit SHA for the initial release
> chore: remove version hardcoding for vercel

- packages/sdk/cloudflare/example/package.json
> fix: bump cloudflare sdk dep

- packages/sdk/vercel/src/createPlatformInfo.ts
- release-please-config.json
I ended up using the release-please extra files instead of the `.default`. The edge environment doesn't seem to agree with TS expectations here, so `.default` would violate the local typings.
The test file still loads from pacakge.json, which passes here, and should pass as the release PRs update things. If the module name changed, it would fail, which is good actually.
After this is merged we can check the release PR.
> feat: Use version number from release process instead of package.json.

- .github/workflows/akamai.yml
- README.md
- packages/sdk/akamai/README.md
- packages/sdk/akamai/package.json
- packages/sdk/akamai/src/createPlatformInfo.test.ts
- packages/sdk/akamai/src/createPlatformInfo.ts
- packages/sdk/akamai/tsconfig.ref.json
- release-please-config.json
Adding the Create platform class and test for the Akamai SDK
Added `@launchdarkly/js-server-sdk-common-edge` dependency
Removed unnecessary file inclusion from tsconfig
> feat: Adding CreatePlatformInfo for Akamai SDK

- package.json
This PR removes the newly added Vercel examples from the yarn workspace to fix the build. I confirmed that `yarn && yarn build` did not result in any errors.
> fix: remove Vercel examples from yarn workspace to fix build

- README.md
- packages/sdk/akamai-base/README.md
- packages/sdk/akamai-edgekv/README.md
Update readme badge links for the Akamai Base and Akamai EdgeKV SDKs
Old:
New:
> chore: update readme badge links

- .github/ISSUE_TEMPLATE/package-stores-node-server-sdk-redis--bug_report.md
- .github/ISSUE_TEMPLATE/package-stores-node-server-sdk-redis--feature_request.md
- .github/workflows/node-redis.yml
- README.md
- package.json
- packages/store/node-server-sdk-redis/LICENSE
- packages/store/node-server-sdk-redis/README.md
- packages/store/node-server-sdk-redis/jest.config.js
- packages/store/node-server-sdk-redis/package.json
- packages/store/node-server-sdk-redis/tsconfig.json
- tsconfig.json
First note that this is NOT targeting main. It is targeting a feature branch.
Scaffolds the location for the node redis package. This just makes packages and updates readmes and things.
This does not add it to the release-please configuration. That will be done when it is ready to be released.
The existing package uses the "redis" package. For this implementation I am planning to use "ioredis" because it has sentinel support.
> chore: Scaffold node redis store package.

- packages/sdk/akamai-base/src/index.ts
- packages/sdk/akamai-edgekv/src/index.ts
- packages/shared/akamai-edgeworker-sdk/src/index.ts
Exported typescript types from Akamai SDK
> feat: Exported typescript types for Akamai SDK

- packages/sdk/vercel/examples/complete/lib/ldEdgeClient.ts
Renames the edgeClient variable to edgeConfigClient to be more descriptive and avoid confusion.
> chore: rename Edge Config client

- packages/sdk/vercel/examples/complete/middleware.ts
Avoids modifying req.nextUrl by constructing new URLs instead.
I did not actually test these changes, please verify before merging.
> fix: avoid modifying req.nextUrl

- .github/ISSUE_TEMPLATE/package-sdk-akamai-base--bug_report.md
- .github/ISSUE_TEMPLATE/package-sdk-akamai-base--feature_request.md
- .github/ISSUE_TEMPLATE/package-sdk-akamai-edgekv--bug_report.md
- .github/ISSUE_TEMPLATE/package-sdk-akamai-edgekv--feature_request.md
- .github/ISSUE_TEMPLATE/package-sdk-akamai-edgeworker-sdk--bug_report.md
- .github/ISSUE_TEMPLATE/package-sdk-akamai-edgeworker-sdk--feature_request.md
Adding issue templates for the following sdks
- Akamai Base
- Akamai EdgeKV
- Akamai Edgworker SDK
> chore: Add issue templates for Akamai SDKs

- packages/sdk/akamai-base/README.md
- packages/sdk/akamai-edgekv/README.md
- packages/shared/akamai-edgeworker-sdk/README.md
- release-please-config.json
Remove `release-as` from Akamai SDKs
Update documentation to indicate that the SDK is changing from `alpha -> beta`
> feat: Release beta version of Akamai SDKs

- contract-tests/BigSegmentTestStore.js
- contract-tests/index.js
- contract-tests/log.js
- contract-tests/package.json
- contract-tests/sdkClientEntity.js
- packages/sdk/server-node/src/index.ts
- packages/shared/common/__tests__/logging/BasicLogger.test.ts
- packages/shared/common/src/logging/BasicLogger.ts
- packages/shared/sdk-server/src/BigSegmentsManager.ts
- packages/shared/sdk-server/src/evaluation/Evaluator.ts
fix: Correctly handle cached big segment status for excluded users.
fix: Handle log formatting correctly when there is a prefix. 
chore: Implement support for big segments contract tests.
fix: Do not query big segment status for a context which doesn't match the big segment kind. Verify the kind before checking the generation.
> fix: Correctly handle excluded big segments.

- packages/sdk/akamai-base/package.json
- packages/sdk/akamai-base/src/index.ts
- packages/sdk/akamai-edgekv/package.json
- packages/sdk/akamai-edgekv/src/index.ts
- packages/sdk/vercel/package.json
- packages/sdk/vercel/src/createPlatformInfo.test.ts
- packages/sdk/vercel/src/createPlatformInfo.ts
- scripts/replace-version.sh
Workaround for https://github.com/googleapis/release-please/issues/1978
Basically this just runs a post processing step to put the version number into the build.
So we build as normal, then it replaces `__LD_VERSION__` in the built package with the version from the package.json.
Once the release-please bug is fixed we can remove this workaround.
> chore: Workaround x-release-please-version problem.

- packages/sdk/vercel/examples/complete/app/missing-edge-config/page.tsx
Minor url fix reported in [issue 140](https://github.com/launchdarkly/js-core/issues/140).
> chore: fix vercel example link

- packages/sdk/server-node/package.json
I was trying to upgrade our Next.js application to use `@launchdarkly/node-server-sdk`, but was running into the following error when trying to build our app:
```
Module not found: Default condition should be last one
```
According to https://nodejs.org/api/packages.html#conditional-exports, the `default` conditional export should be the last one listed. After making that change the app built successfully. I created a simple reproduction here: https://github.com/seanparmelee/ld-server-nextjs.
> fix: move "default" conditional exports to be last

- contract-tests/index.js
- contract-tests/sdkClientEntity.js
This adds support for the `user-type` capability of the contract tests.
All tests pass.
> chore: Add support for user-type contract tests.

- scripts/replace-version.sh
The workaround to replace sdk versions in [replace-version.sh](https://github.com/launchdarkly/js-core/blob/main/scripts/replace-version.sh#L14) does not work locally on OS X because the sed command is not posix compliant. This breaks yarn build locally on os x.
On os x, `sed -i` expects the next argument to a backup file extension.
On Linux/Unix, it does not.
This ticket implements a workaround for the workaround. As you can see, this is a rabbit hole which eventually is best solved by not using this script at all.
> fix: broken local build due to sed -i warning

- packages/shared/sdk-client/jest-setupFilesAfterEnv.ts
- packages/shared/sdk-client/jest.config.js
- packages/shared/sdk-client/jest.config.json
- packages/shared/sdk-client/package.json
- packages/shared/sdk-client/src/api/LDEmitter.test.ts
- packages/shared/sdk-client/src/api/LDEmitter.ts
- packages/shared/sdk-client/src/api/LDEventTarget.ts
- packages/shared/sdk-client/tsconfig.json
* Improved emitter design
* Improved jest config
* Added unit tests
> chore: improved LDEmitter

- packages/shared/sdk-server/package.json
Updating semver to latest. The reason it was pinned to 7.5.0 was because 7.5.0 introduced require('util') without the node: prefix. This has been fixed in [7.5.1](https://github.com/npm/node-semver/releases/tag/v7.5.1) so we'll update to latest which is 7.5.4.
> chore: bump semver dep

- packages/shared/sdk-server/__tests__/LDClient.migrations.test.ts
- packages/shared/sdk-server/package.json
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/api/LDClient.ts
- packages/shared/sdk-server/src/api/data/LDMigrationStage.ts
- packages/shared/sdk-server/src/api/data/index.ts
For now I am adding this to server common, which means that edge SDKs would inherit the behavior. We may not want that, because they don't support events, but I can always exclude it or move the implementation.
> feat: Add migrationVariation method.

- .eslintrc.js
Exclude test files from the eslint no-extraneous-deps rule. This is failing in cloudflare index.test.ts where eslint insists 'miniflare' should be in deps, not devDep:
```js
'import/no-extraneous-dependencies': [
'error',
{
devDependencies: ['**/jest*.ts', '**/*.test.ts'],
},
],
```
> chore: fix eslint extraneous dep error

- packages/shared/sdk-server/__tests__/LDClient.evaluation.test.ts
- packages/shared/sdk-server/__tests__/integrations/test_data/TestData.test.ts
- packages/shared/sdk-server/src/integrations/test_data/TestDataFlagBuilder.ts
User targets require special logic to put the variation/values into `targets` instead of just in `contextTargets`. This was not being done, so user specific targets were not evaluating correctly.
Github issue: https://github.com/launchdarkly/node-server-sdk/issues/283
> fix: Ensure that test data user targets are handled correctly.

- .github/workflows/server-node.yml
Node 19+ has a bug currently with connection resets. This only affects testing (because we have inbound connections), but I am downgrading to avoid it until it is resolved.
> chore: Update the node version used for CI.

- packages/sdk/cloudflare/src/createPlatformInfo.ts
- packages/sdk/server-node/src/platform/NodeInfo.ts
- packages/sdk/vercel/src/createPlatformInfo.ts
- packages/shared/akamai-edgeworker-sdk/src/__tests__/platform/info/index.test.ts
- packages/shared/akamai-edgeworker-sdk/src/platform/info/index.ts
- packages/shared/common/src/api/platform/Info.ts
- packages/shared/sdk-server/__tests__/data_sources/defaultHeaders.test.ts
- packages/shared/sdk-server/src/data_sources/defaultHeaders.ts
Currently `NodeJSClient` is being used as the user agent for all server SDKs.
This was not apparent because only node was sending events. Events are being added to Vercel and it revealed this issue.
> feat: Allow specifying the user agent per-sdk implementation.

- .release-please-manifest.json
- packages/sdk/vercel/package.json
- release-please-config.json
Release-As was left in the release please config.
Two versions have actually been released since then. They released fine, but the changelog was getting incorrect headers.
> chore: Unpin vercel release version to allow correct change log generation.

- packages/shared/sdk-server/src/api/LDClient.ts
We got feedback from a customer that they were confused by the "goals" language in our SDK docs, which we now call "metrics." This clarifies that goals = metrics and A/B testing = Experimentation.
Story details: https://app.shortcut.com/launchdarkly/story/213100
> chore: clarify that "goals" are the same as "metrics"

- packages/sdk/akamai-base/example/tsconfig.json
- packages/sdk/akamai-base/tsconfig.json
I am putting these back to nodenext. After pinning typescript I found that rollup and typescript are not agreeing on what these options should be set to.
> chore: Change akamai module to nodenext

- package.json
- packages/sdk/akamai-base/example/package.json
- packages/sdk/akamai-base/package.json
- packages/sdk/akamai-edgekv/example/package.json
- packages/sdk/akamai-edgekv/package.json
- packages/sdk/cloudflare/example/package.json
- packages/sdk/cloudflare/package.json
- packages/sdk/server-node/package.json
- packages/sdk/vercel/examples/complete/package.json
- packages/sdk/vercel/package.json
- packages/shared/akamai-edgeworker-sdk/package.json
- packages/shared/akamai-edgeworker-sdk/src/featureStore/index.ts
- packages/shared/common/package.json
- packages/shared/sdk-server-edge/package.json
- packages/shared/sdk-server-edge/src/api/EdgeFeatureStore.ts
- packages/shared/sdk-server/package.json
- packages/store/node-server-sdk-dynamodb/package.json
- packages/store/node-server-sdk-redis/package.json
Add new data kind support as well as a couple error handling changes.
> feat: New data kinds for edge SDKs.

- contract-tests/index.js
- contract-tests/sdkClientEntity.js
- packages/shared/sdk-server/__tests__/MigrationOpEvent.test.ts
- packages/shared/sdk-server/__tests__/MigrationOpTracker.test.ts
- packages/shared/sdk-server/src/Migration.ts
- packages/shared/sdk-server/src/MigrationOpEventConversion.ts
- packages/shared/sdk-server/src/MigrationOpTracker.ts
- packages/shared/sdk-server/src/api/data/LDMigrationDetail.ts
- packages/shared/sdk-server/src/api/data/LDMigrationOpEvent.ts
The migration_op event now has a measurement for which "origins" were invoked. Basically was the 'new' method, the 'old' method, or both executed.
This is because from other data you cannot safely infer what was executed. We need to know total executions in order to properly analyze results.
> feat: Add invoked measurement.

- packages/shared/sdk-server/__tests__/MigrationOpEvent.test.ts
- packages/shared/sdk-server/__tests__/MigrationOpTracker.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/Migration.ts
- packages/shared/sdk-server/src/MigrationOpTracker.ts
- packages/shared/sdk-server/src/api/LDClient.ts
- packages/shared/sdk-server/src/api/data/LDMigrationVariation.ts
- packages/shared/sdk-server/src/api/data/index.ts
Was reviewing my code and Mathew's and noticed some inconsistencies in how we approach the consistency check. Node correctly only did the check when sampled, but exposed more information than we want. So we have changed the two SDKs to be consistent with each other. So go now only samples when we want, and node will expose less information,
> feat: Refactor variation method and consistency tracking.

- packages/shared/sdk-server/src/Migration.ts
Migration method would get called twice during latency measurement.
> fix: Fix double call when platform support performance API.

- packages/shared/akamai-edgeworker-sdk/src/__tests__/testData.json
- packages/shared/sdk-server/__tests__/LDClient.allFlags.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
The node-server-sdk was not using the newer `clientSideAvailability`, but `clientSide`. In porting to TS that logic was retained. This updates it to use the newer field.
> fix: Use clientSideAvailability instead of clientSide for filtering client side flags.

- contract-tests/index.js
- contract-tests/sdkClientEntity.js
- packages/shared/common/src/api/data/LDEvaluationDetail.ts
- packages/shared/sdk-server/__tests__/LDClient.evaluation.test.ts
- packages/shared/sdk-server/__tests__/LDClient.migrations.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/Migration.ts
- packages/shared/sdk-server/src/api/LDClient.ts
- packages/shared/sdk-server/src/api/data/LDMigrationVariation.ts
- packages/shared/sdk-server/src/evaluation/ErrorKinds.ts
This adds typed variation methods. 
This works for both JS and TS, but may be especially nice for those that want to be more type safe in typescript.
resolves #285
> feat: Add typed variation methods.

- .github/workflows/mocks.yml
- actions/ci/action.yml
- packages/shared/common/package.json
- packages/shared/mocks/package.json
CI failed because `yarn workspaces foreach -pR --topological-dev --from '@launchdarkly/xxx' run build`. This is because `topological-dev` instructs yarn to build all deps (prod & dev) prior to running build in the current workspace. Since `mocks` need types from `common` this fails.
This pr adds a `build-types` command to common which gets run prior to mocks `build` command to ensure common types exist for mocks to be built successfully.
> fix: yarn topological dev build

- contract-tests/sdkClientEntity.js
I have done some investigation and found that the intermittent issues with contract tests seem to be related to how the test harness handles them. We do not actually test them using the test harness, so I am disabling them now to improve CI and release robustness.
I've basically been running the contract tests in a loop. Usually they fail in a few hours, but with diagnostic opt out they ran overnight.
I was testing them in combination with some other robustness improvements, but I am re-testing now with just this change. Those changes can be independent. 
Once we know what is going on the test harness side we should be able to re-enable these, but it likely isn't worth doing unless there are some tests for them.
> chore: Disable diagnostic events when running contract tests.

- packages/shared/sdk-server/src/api/data/LDMigrationOpEvent.ts
- packages/shared/sdk-server/src/api/index.ts
> fix: Export migration APIs.

- packages/shared/sdk-server/src/Migration.ts
*** I cannot validate tests execute due to following error during npm install:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@launchdarkly%2fprivate-js-mocks - Not found
npm ERR! 404 
npm ERR! 404  '@launchdarkly/private-js-mocks@0.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'sdk-server'
This fixes the following error on Node.js v14:
ReferenceError: performance is not defined
at Migration.trackLatency (/<project>/node_modules/@launchdarkly/js-server-sdk-common/dist/Migration.js:245:13)
Since `"undefined" !== undefined` 😛 
The `performance` module is available in …
> fix: Correct comparison for typeof check.

- packages/sdk/react-native/src/ReactNativeLDClient.ts
- packages/sdk/react-native/src/platform.ts
- packages/sdk/react-native/src/react-native-sse/EventSource.ts
- packages/sdk/react-native/src/react-native-sse/types.ts
Pass `errorFilter` to rn eventSource to specify custom retry logic and error handling.
> chore: Use error filter in rn event source

- packages/shared/sdk-server/__tests__/data_sources/FileDataSource.test.ts
- packages/shared/sdk-server/src/data_sources/FileDataSource.ts
When using FileData you have the option of just providing values. The pre-typescript SDK was liberal with what it considered an update and it would emit updates as things changed.
Some improvements to prevent spurious update events were added in typscript and these interfered with the basic way the FileData implementation works.
This PR makes a couple updates:
1.) If the value of a "flagValue" changes, then we will increment the version associated with it.
2.) If the value of a "flagValue" does not change, then we will not increment the version.
This should mean when values change the version will change. Standard flag/segment JSON must update their versions manually.
This will add some performance overhead.
This addresses #310
> fix: Increment version for changing flagValues

- packages/sdk/react-native/src/provider/setupListeners.ts
- packages/shared/common/src/api/data/LDFlagChangeset.ts
- packages/shared/common/src/api/data/index.ts
- packages/shared/mocks/src/streamingProcessor.ts
- packages/shared/sdk-client/src/LDClientImpl.storage.test.ts
- packages/shared/sdk-client/src/LDClientImpl.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/api/LDClient.ts
- packages/shared/sdk-client/src/api/LDEmitter.test.ts
- packages/shared/sdk-client/src/api/LDEmitter.ts
- packages/shared/sdk-client/src/configuration/Configuration.test.ts
- packages/shared/sdk-client/src/diagnostics/createDiagnosticsInitConfig.test.ts
- packages/shared/sdk-client/src/diagnostics/createDiagnosticsInitConfig.ts
- packages/shared/sdk-client/src/evaluation/fetchFlags.test.ts
- packages/shared/sdk-client/src/evaluation/fetchFlags.ts
- packages/shared/sdk-client/src/events/EventFactory.ts
- packages/shared/sdk-client/src/types/index.ts
- packages/shared/sdk-client/src/utils/index.ts
This implements feedback from #326.
* Run synchronization logic for all `change` events.
* Removed `ready` event and use `change` instead.
* Callback argument for `change` is now just a string array of flag keys.
* Removed config options `stream` and `useReport` for now for this alpha.
> chore: localstorage pr feedback

- packages/shared/sdk-client/src/LDClientImpl.storage.test.ts
- packages/shared/sdk-client/src/LDClientImpl.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/types/index.ts
Implement tombstoning based on feedback frrom #326.
> chore: implement tombstoning

- .github/workflows/sdk-client.yml
This is needed for the sdk-client package to be published to npm.
> fix: add ga workflow to publish sdk-client.

- packages/shared/common/src/internal/stream/index.ts
No new functionality has been added (only types import/export refactoring).
https://github.com/launchdarkly/js-core/issues/345 https://github.com/launchdarkly/js-core/issues/347
Remove the usage of [type modifiers on import names](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names) to improve backwards compatibility with early versions of TypeScript.
The obvious solution would be upgrading the TypeScript version in the consumer, but this is not always easy (it's not in our case). [More info here](https://github.com/microsoft/TypeScript/issues/25778).
> fix: remove type modifiers on imports for better TS compatibility

- PROVENANCE.md
- packages/sdk/akamai-base/README.md
- packages/sdk/akamai-edgekv/README.md
- packages/sdk/cloudflare/README.md
- packages/sdk/react-native/README.md
- packages/sdk/server-node/README.md
- packages/sdk/vercel/README.md
- packages/shared/common/README.md
- packages/shared/sdk-server-edge/README.md
- packages/shared/sdk-server/README.md
- packages/store/node-server-sdk-dynamodb/README.md
- packages/store/node-server-sdk-redis/README.md
Drafting up documentation for how consumers may use the SLSA framework to verify SDK packages published with provenance to improve supply chain security. 
> docs: adding SLSA verification steps to READMEs

- packages/sdk/react-native/example/e2e/starter.test.ts
- packages/sdk/react-native/example/src/welcome.tsx
- packages/shared/common/__tests__/internal/events/EventProcessor.test.ts
- packages/shared/common/src/internal/events/EventProcessor.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/api/ConnectionMode.ts
- packages/shared/sdk-client/src/api/LDClient.ts
- packages/shared/sdk-client/src/api/LDOptions.ts
- packages/shared/sdk-client/src/api/index.ts
- packages/shared/sdk-client/src/configuration/Configuration.test.ts
- packages/shared/sdk-client/src/configuration/Configuration.ts
- packages/shared/sdk-client/src/configuration/validators.ts
- packages/shared/sdk-client/src/diagnostics/createDiagnosticsInitConfig.test.ts
- packages/shared/sdk-client/src/diagnostics/createDiagnosticsManager.ts
- packages/shared/sdk-client/src/events/createEventProcessor.ts
This adds offline support for the RN SDK through ConnectionMode.
```tsx
/**
* Sets the mode to use for connections when the SDK is initialized.
*
* Defaults to streaming.
*/
initialConnectionMode?: ConnectionMode; // in api/LDOptions.ts
/**
* Sets the SDK connection mode.
*
* @param mode - One of supported {@link ConnectionMode}. By default, the SDK uses 'streaming'.
*/
setConnectionMode(mode: ConnectionMode): void; // in api/LDClient.ts
```
> fix: Add RN SDK offline support through ConnectionMode.

- packages/sdk/react-native/example/App.tsx
- packages/sdk/react-native/example/tsconfig.json
- packages/sdk/react-native/src/ReactNativeLDClient.test.ts
- packages/sdk/react-native/src/ReactNativeLDClient.ts
- packages/sdk/react-native/src/platform/autoEnv.ts
- packages/sdk/react-native/src/provider/LDProvider.test.tsx
- packages/sdk/react-native/src/provider/LDProvider.tsx
- packages/shared/sdk-client/src/LDClientImpl.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/api/LDClient.ts
- packages/shared/sdk-client/src/api/LDOptions.ts
- packages/shared/sdk-client/src/configuration/Configuration.test.ts
- packages/shared/sdk-client/src/configuration/Configuration.ts
- packages/shared/sdk-client/src/configuration/validators.ts
- packages/shared/sdk-client/src/evaluation/fetchFlags.test.ts
These are discovered after the docs PR review:
* Client sdk default baseUri should be clientsdk.launchdarkly instead of sdk.launchdarkly.
* Add getConnectionMode.
* Remove identify hash arg.
* Change rn default logging to info.
* Add debug config option.
* Add comments about autoEnv applicationInfo.
* Remove LDProvider context prop.
> fix: Improvements and fixes from docs review.

- packages/shared/sdk-client/src/LDClientImpl.storage.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/api/LDClient.ts
- packages/shared/sdk-client/src/api/LDEmitter.test.ts
- packages/shared/sdk-client/src/api/LDEmitter.ts
* Corrected close to return a Promise. 
* Removed redundant EventName `identifying`.
* Add missing type for getConnectionMode.
> fix: Minor fixes from docs pr review.

- packages/sdk/react-native/example/package.json
- packages/sdk/react-native/example/src/welcome.tsx
- packages/sdk/react-native/example/yarn.lock
- packages/sdk/react-native/src/polyfills/CustomEvent.ts
- packages/sdk/react-native/tsconfig.json
This is a babel issue related to the event-target-shim package. For unknown reasons, in Expo 50, the metro bundler is unable to transpile event-target-shim correctly resulting in the error below.
```sh
ERROR  TypeError: Super expression must either be null or a function, js engine: hermes
...
info Opening .../node_modules/@launchdarkly/react-native-client-sdk/dist/src/polyfills/CustomEvent.js
```
Thankfully the event-target-shim package offers a transpiled es5 version which seems to work. We'll use that instead.
> fix: Babel TypeError due to event-target-shim

- packages/sdk/react-native/example/README.md
- packages/sdk/react-native/example/build-run-detox.sh
- packages/sdk/react-native/example/e2e/starter.test.ts
- packages/sdk/react-native/example/package.json
- packages/sdk/react-native/example/yarn.lock
Detox was broken after upgrading the example app to RN0.73. The error was very cryptic and the solution equally so:
```
[CP-User] [Hermes] Replace Hermes for the right configuration, if needed
```
Solution: Delete `ios/.xcode.env.local`. https://github.com/facebook/react-native/issues/42112#issuecomment-1884536225
> fix: Fix Detox e2e tests broken after 0.73 update.

- packages/sdk/server-node/__tests__/platform/NodeRequests.test.ts
- packages/sdk/server-node/src/platform/NodeResponse.ts
> fix: Fix an issue where failed http requests could cause an unhandled promise rejection.

- .github/workflows/release-please.yml
- actions/full-release/action.yml
This PR is to prevent 8.x docs from overwriting 9.x docs.
In the future we may want to consider docs for multiple versions, but we do not currently support that.
> chore: Do not publish docs on maintenance branch.

- packages/shared/sdk-client/src/LDClientImpl.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
> fix: Bug in sdk-client where withReasons was not passed to streamer.

- package.json
- packages/sdk/vercel/examples/complete/.eslintrc.json
- packages/sdk/vercel/examples/complete/middleware.ts
- packages/sdk/vercel/examples/complete/package.json
- packages/sdk/vercel/examples/route-handler/next.config.js
- packages/sdk/vercel/examples/route-handler/package.json
- packages/sdk/vercel/package.json
- packages/sdk/vercel/src/utils/mockEdgeConfigClient.ts
Fixes #379 . I have tested this locally and verified the type errors are fixed and the example application (complete) still works.
> fix: Update to major version of @vercel/edge-config

- .sdk_metadata.json
This adds a (prototype, subject to change) `.sdk_metadata.json` dotfile to the repo. 
It contains metadata about each of the SDKs present here. 
Things to think about:
- Filename, being a dotfile, ok?
- Location, root of repo, makes sense?
- Contents: how to tell the tool which releases belong to each SDK? (currently: specify the tag prefix, and the tool will filter based on that)
> chore: add .sdk_metadata.json to repo

- packages/sdk/vercel/examples/complete/package.json
- packages/sdk/vercel/examples/route-handler/package.json
We updated @vercel/edge-config package to use the major version in this [pr](https://github.com/launchdarkly/js-core/pull/393) however I overlooked updating the corresponding example apps to use the workspace versions of our vercel sdk.
> chore: Update vercel examples to use workspace packages.

- packages/sdk/cloudflare/jsr.json
I'm manually updating the version in jsr.json and publishing for now since we are blocked by a github linking issue in the jsr portal.
https://jsr.io/@launchdarkly/cloudflare-server-sdk
> chore: Update Cloudflare SDK version in jsr.json.

- release-please-config.json
Update the version to 9.3.0 to reflect the addition of hooks.
> chore: Change Node server SDK to 9.3.0

- .sdk_metadata.json
Since we have a Node.js client SDK, it makes sense to have the names be:
Node.js Server SDK
Node.js Client SDK
(I think?)
> chore: add 'server' to Node.js SDK name

- scripts/publish-jsr.sh
This is needed otherwise the gha [fails](https://github.com/launchdarkly/js-core/actions/runs/8758581209/job/24039697071#step:10:51):
```bash
npm WARN exec The following package was not found and will be installed: jsr@0.12.2
Downloading JSR binary...
Download completed
Checking for slow types in the public API...
error: Aborting due to uncommitted changes. Check in source code or run with --allow-dirty
Child process exited with: 1
jsr publish failed
Error: Process completed with exit code 1.
```
> chore: Skip yarn pack for jsr publish.

- .github/workflows/manual-publish.yml
- .prettierignore
- scripts/publish-jsr.sh
The root cause is .yarnrc.yml being modified because of the addition of npmRegistryServer:
```shell
Publishing jsr: @launchdarkly/cloudflare-server-sdk
diff --git a/.yarnrc.yml b/.yarnrc.yml
index 5a857be..7cbcb75 100644
--- a/.yarnrc.yml
+++ b/.yarnrc.yml
@@ -4,10 +4,14 @@ npmPublishAccess: public
npmScopes:
jsr:
-    npmRegistryServer: 'https://npm.jsr.io/'
+    npmRegistryServer: "https://npm.jsr.io/"
+  launchdarkly:
+    npmAlwaysAuth: true
+    npmAuthToken: ***
+    npmRegistryServer: "https://registry.npmjs.org/"
plugins:
- path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
-    spec: '@yarnpkg/plugin-workspace-tools'
+    spec: "@yarnpkg/plugin-workspace-tools"
```
> chore: Allow dirty for jsr publish.

- packages/shared/sdk-client/src/LDClientImpl.timeout.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
Make the message more actionable.
> fix: Adjust identify timeout message.

- packages/sdk/cloudflare/src/createPlatformInfo.ts
- release-please-config.json
This embeds the package name and version directly into the source instead of attempting to import the package.json. This has greater compatibility and depends on release-please to update the version.
> fix: Include name and version in platform.

- packages/sdk/server-node/src/platform/NodeRequests.ts
Without these set the event source retries every second, which is not the desired behavior.
> fix: Configure max backoff and jitter ratio to ensure exponential backoff.

- packages/sdk/server-node/package.json
This version includes fixes which improve error handling and shutdown of SSE streams.
Fixes #458
> fix: Update launchdarkly-eventsource to 2.0.3.

- packages/shared/sdk-server/__tests__/cache/LruCache.test.ts
- packages/shared/sdk-server/src/cache/LruCache.ts
> fix: LRU cache memory leak.

- packages/shared/common/__tests__/cancelableTimeoutPromise.test.ts
- packages/shared/common/src/utils/cancelableTimedPromise.ts
- packages/shared/common/src/utils/index.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
The current timedPromise doesn't provide access to the handle, so it cannot cancel the timer. The timer itself will not have a harmful result, but it is an open handle. Open handles often prevent runtimes from exiting. For instance initializing something like the node server with a really long timeout may keep the process open for that entire timeout even if the SDK initialized.
I am adding this as a new function, which node server will then migrate to. RN can of course migrate as well, but this change will be independent. 
I noticed this unit testing the openfeature-node-provider with a timeout and each test had a remaining open handle.
> feat: Add support for a cancel-able timeout.

- package.json
Seems like v3.3.0 of jsonc-parser causes an error in rollup-plugin-esbuild:
```bash
[!] SyntaxError: Named export 'parse' not found. The requested module 'jsonc-parser' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'jsonc-parser';
const { parse } = pkg;
/js-core/node_modules/rollup-plugin-esbuild/dist/index.mjs:11
import { parse } from "jsonc-parser";
^^^^^
```
> fix: Pin jsonc-parser to fix cloudflare rollup build.

- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/api/Collector.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/SessionReplay.ts
- packages/telemetry/browser-telemetry/src/inspectors.ts
This is prototype code.
Adds custom events for flag evaluations, flag updates, and for errors.
> feat: Add custom rrweb events.

- packages/telemetry/browser-telemetry/__tests__/SessionBuffer.test.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/ContinuousReplay.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/RollingBuffer.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/RollingReplay.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/SessionBuffer.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/SessionReplay.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/SessionReplayOptions.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/patches.ts
Prototype code.
Usage:
```
const session = new SessionReplay();
const telemetry = initializeTelemetry({collectors: [session]});
const client = initialize('client-side-id', {
kind: 'user',
key: 'example-user'
}, {
inspectors: telemetry.inspectors(),
});
telemetry.register(client);
```
> feat: Add continuous session replay capture.

- packages/sdk/server-node/__tests__/LDClientNode.listeners.test.ts
- packages/sdk/server-node/__tests__/LDClientNode.test.ts
- packages/sdk/server-node/src/LDClientNode.ts
- packages/shared/akamai-edgeworker-sdk/src/api/LDClient.ts
- packages/shared/akamai-edgeworker-sdk/src/utils/createCallbacks.ts
- packages/shared/sdk-server-edge/src/api/LDClient.ts
- packages/shared/sdk-server-edge/src/api/createCallbacks.test.ts
- packages/shared/sdk-server-edge/src/api/createCallbacks.ts
When there are no error event handlers the server SDKs should log the errors instead.
This behavior was missed during the typescript re-write.
We may want to consider if we always want to log errors, but I understand the logic of this. If you are listening to this, then you may also be logging it, and if you are not logging it, then you are at least getting the event.
I imagine most consumers are not using the error events.
> fix: Log errors when there is no error event handler.

- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/api/Collector.ts
- packages/telemetry/browser-telemetry/src/collectors/dom/ClickCollector.ts
- packages/telemetry/browser-telemetry/src/collectors/dom/KeypressCollector.ts
- packages/telemetry/browser-telemetry/src/collectors/http/fetch.ts
- packages/telemetry/browser-telemetry/src/collectors/http/xhr.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/ContinuousReplay.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/RollingReplay.ts
- packages/telemetry/browser-telemetry/src/collectors/rrweb/SessionReplay.ts
Ensure that the session replay session ID is the same as the error events.
This is prototype code.
> fix: Use consistent session id for session replay.

- packages/sdk/react-native/README.md
- packages/sdk/react-native/example/README.md
- packages/sdk/react-native/example/package.json
After this PR the example React Native app will work correctly with Android. Most of the PR is documentation.
> feat: Update expo and RN version used in example.

- packages/sdk/react-native/src/platform/ConnectionManager.test.ts
- packages/sdk/react-native/src/platform/ConnectionManager.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/api/ConnectionMode.ts
This adds a connection manager which is used to handle application state and network state and determine the desired connection mode.
> feat: Add connection mananger.

- packages/sdk/react-native/src/RNOptions.ts
- packages/sdk/react-native/src/ReactNativeLDClient.test.ts
- packages/sdk/react-native/src/ReactNativeLDClient.ts
- packages/sdk/react-native/src/index.ts
- packages/sdk/react-native/src/platform/ConnectionManager.ts
- packages/sdk/react-native/src/platform/PlatformEncoding.ts
- packages/sdk/react-native/src/platform/PlatformInfo.ts
- packages/sdk/react-native/src/platform/PlatformRequests.ts
- packages/sdk/react-native/src/platform/PlatformStorage.ts
- packages/sdk/react-native/src/platform/index.ts
- packages/shared/sdk-client/src/LDClientImpl.events.test.ts
- packages/shared/sdk-client/src/LDClientImpl.test.ts
- packages/shared/sdk-client/src/LDClientImpl.timeout.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/LDClientImpl.variation.test.ts
- packages/shared/sdk-client/src/api/LDClient.ts
This fixes the field visibility on a number of what should have been private or readonly fields.
This is technically a breaking change because the implementation types were exposed, but they are not part of the interface.
One attribute that is in the interface is the logger, and it has been marked as readonly now, which is also a breaking change.
Setting or manipulating any of these fields would have resulted in potentially inconsistent internal state.
> fix: Fix field visibility.

- packages/shared/sdk-client/src/configuration/Configuration.test.ts
- packages/shared/sdk-client/src/configuration/validators.ts
Forgot to add the max cached context to the validator and realized when bench testing.
> chore: adding max contexts validator

- packages/shared/sdk-client/src/api/LDIdentifyOptions.ts
In the strictest sense this would be a breaking change, but in the practical I think it is not likely to be.
The way this would be breaking is if someone was using this for something other than just passing to the identify function. This would be somewhat unusual.
Example:
```
interface MyOptions: {
timeout: number;
}
let myOptions: MyOptions = someLdIdentifyOptions;
```
For standard usage this will not be breaking. 
I am tagging this as a feat instead of a fix to prevent any breakage for someone floating patches and also doing unusual things with the type.
> feat: Make timeout optional in LDIdentifyOptions.

- packages/shared/sdk-server/__tests__/store/serialization.test.ts
- packages/shared/sdk-server/src/store/serialization.ts
During the typescript implementation null values were removed during JSON de-serialization. This was over-zealous as variations can be JSON which contains null values.
This retains null value removal for everything aside from variations.
The reason this was originally done is to simplify all code which interacts with the data model (It only needs to check undefined versus null/undefined.). It also simplifies the ability to produce a compact representation that omits any null fields.
In the future we may want to consider removing this behavior.
Fixes #568
> fix: Correctly handle null values in JSON variations.

- packages/shared/sdk-client/src/LDClientImpl.ts
This code was orphaned in some refactoring and should be removed.
> chore: Remove unused function in common client-side LDClientImpl.

- packages/shared/sdk-client/__tests__/LDClientImpl.changeemitter.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/LDEmitter.ts
> feat: adds support for individual flag change listeners

- packages/sdk/browser/__tests__/BrowserDataManager.test.ts
- packages/sdk/react-native/__tests__/MobileDataManager.test.ts
- packages/shared/sdk-client/__tests__/LDCLientImpl.inspections.test.ts
- packages/shared/sdk-client/__tests__/inspection/InspectionManager.test.ts
- packages/shared/sdk-client/__tests__/inspection/createSafeInspector.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/api/LDClient.ts
- packages/shared/sdk-client/src/api/LDInspection.ts
- packages/shared/sdk-client/src/api/LDOptions.ts
- packages/shared/sdk-client/src/configuration/Configuration.ts
- packages/shared/sdk-client/src/configuration/validators.ts
- packages/shared/sdk-client/src/context/addAutoEnv.ts
- packages/shared/sdk-client/src/context/ensureKey.ts
- packages/shared/sdk-client/src/flag-manager/FlagUpdater.ts
- packages/shared/sdk-client/src/inspection/InspectorManager.ts
- packages/shared/sdk-client/src/inspection/createSafeInspector.ts
- packages/shared/sdk-client/src/inspection/getInspectorHook.ts
- packages/shared/sdk-client/src/inspection/messages.ts
The flag usage and identify were able to be implemented in terms of hooks.
The flag configuration related inspectors had to be implemented directly. It would be ideal to figure out how to gauge demand for this functionality and simply remove it when we deprecated hooks if demand is low.
> feat: Add support for inspectors.

- packages/shared/common/package.json
- packages/shared/common/rollup.config.js
- packages/shared/common/tsconfig.json
- packages/shared/sdk-client/src/DataManager.ts
When using typescript with moduleResolution set to "node16" types were not loading which are part of the common package.
This relates to changes to the default was in which file resolution occurs. 
This PR will address this, but we will want a better long-term fix. In this PR we convince node that the `.d.ts` files are the correct extension by making a small `package.json` that sets the module type.
In the future we would want the `.d.ts` files to instead be `.d.cts`.
Potentially we can move to tsup: https://tsup.egoist.dev/
But the changes were too extensive for this fix.
Testing:
tsconfig.json
```
{
"$schema": "https://json.schemastore.org/tsconfig",
"_version": "20.1.0",
"compilerOptions": {
"lib": ["es2023"],
"module": "node16",
"target": "es2022",
"strict": true,
"esModuleInterop": …
```
> fix: Fix common package to work with node16 module resolution.

- packages/shared/common/package.json
- packages/shared/sdk-client/package.json
- packages/shared/sdk-client/rollup.config.js
This applies the same fixes to `sdk-client` that were applied to `common`.
This resolves issues with using CJS+Typescript with RN. Our existing test project doesn't use node16/nodenext module resolution.
Can be tested with our example project with this tsconfig.
```
{
"extends": "@react-native/typescript-config/tsconfig.json",
"compilerOptions": {
"allowSyntheticDefaultImports": true,
"jsx": "react-native",
"lib": ["dom", "esnext"],
"module": "nodenext",
"moduleResolution": "nodenext",
"noEmit": true,
"skipLibCheck": true,
"resolveJsonModule": true,
"removeComments": true,
"sourceMap": true,
"strict": true,
"forceConsistentCasingInFileNames": true
},
"exclude": ["e2e"]
}
```
Required installing the base config:
```
yarn add -D @react-native/typescript-config
```
> fix: Update sdk-client rollup configuration to match common

- packages/sdk/browser/__tests__/BrowserDataManager.test.ts
- packages/sdk/browser/__tests__/platform/BrowserEncoding.test.ts
- packages/sdk/browser/__tests__/platform/BrowserHasher.test.ts
- packages/sdk/browser/jest.config.js
- packages/sdk/browser/jest.config.json
- packages/sdk/browser/package.json
- packages/sdk/browser/setup-jest.js
- packages/sdk/browser/src/goals/GoalTracker.ts
- packages/sdk/browser/src/vendor/escapeStringRegexp.ts
- packages/sdk/browser/tsconfig.json
- packages/sdk/browser/tsconfig.test.json
- packages/sdk/cloudflare/jsr.json
chore: Change browser packages testing to use CJS.
feat: Vendor escapeStringRegexp to simplify builds.
SDK-816
> chore: Change testing to use cjs.

- packages/sdk/server-node/src/Emits.ts
This change, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69997, to the `@types/node` package made typings for the emitter stricter and break the builds. Functionally the code is the same.
> fix: Fix incompatibility with @types/node release.

- packages/sdk/browser/src/BrowserClient.ts
- packages/sdk/browser/src/index.ts
- packages/shared/common/__tests__/logging/BasicLogger.test.ts
- packages/shared/common/src/api/logging/BasicLoggerOptions.ts
- packages/shared/common/src/logging/BasicLogger.ts
- packages/shared/sdk-client/__tests__/configuration/Configuration.test.ts
- packages/shared/sdk-client/src/api/LDOptions.ts
This adds support to the common basic logger that makes it more suitable for client SDKs.
Instead of a single destination for all logs you can now control the destination per log level. This allow you to use all the default formatting, log level handling, and log tagging while also getting logs that are nice for use in a browser.
> feat: Enhance basic logger destination support.

- packages/sdk/server-ai/__tests__/LDAIClientImpl.test.ts
- packages/sdk/server-ai/__tests__/LDAIConfigTrackerImpl.test.ts
- packages/sdk/server-ai/__tests__/TokenUsage.test.ts
- packages/sdk/server-ai/jest.config.js
- packages/sdk/server-ai/package.json
- packages/sdk/server-ai/src/LDAIClientImpl.ts
The primary purpose of this was to add unit tests, but it ended up with a bug fix, so that is the PR title.
> fix: Do not include _ldMeta in returned config.

- packages/sdk/browser/src/common.ts
- packages/sdk/browser/src/compat/index.ts
- packages/sdk/browser/src/index.ts
It was proving difficult to ensure that the compat package and the base package exported all the common stuff. So I moved that stuff into a common files and then export that from both.
> fix: Consolidate common exports between base package and compat package.

- packages/sdk/server-ai/src/api/LDAIClient.ts
- packages/sdk/server-ai/src/api/config/LDAIConfig.ts
fix: Update default typings to include enabled.
feat: Include temperature and maxTokens in LDModelConfig.
> fix: Update default typings to include enabled.

- packages/shared/sdk-client/__tests__/LDCLientImpl.inspections.test.ts
- packages/shared/sdk-client/src/LDClientImpl.ts
- packages/shared/sdk-client/src/api/LDInspection.ts
Noticed this difference in behavior when auditing the code for browser telemetry.
> fix: Ensure flag-detail-changed is called for deleted flags.

- packages/sdk/browser/contract-tests/adapter/tsconfig.json
There are some dependencies which have a conflict in type definitions. This only affects the adapter for the contract tests, and doesn't affect runtime, so I am disabling lib checks on that project for the moment. I'll also try to track down what changed.
> chore: Skip lib check for browser adapter.

- packages/sdk/react-universal/example/package.json
- packages/sdk/react-universal/package.json
Newly released types do not compile. Pinning until that can be sorted.
> chore: Pin react types for react-universal.

- packages/sdk/server-ai/__tests__/LDAIClientImpl.test.ts
- packages/sdk/server-ai/examples/bedrock/src/index.ts
- packages/sdk/server-ai/examples/openai/src/index.ts
- packages/sdk/server-ai/src/api/config/LDAIConfig.ts
I will he holding the merge of this until associated changes are ready.
> refactor!: Rename model and providerid to name.

- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
After the client is registered there isn't any further use for the pending events.
> fix: Clear pending events buffer when registered.

- packages/telemetry/browser-telemetry/package.json
- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/index.ts
- packages/telemetry/browser-telemetry/src/stack/StackParser.ts
- packages/telemetry/browser-telemetry/src/vendor/TraceKit.ts
This PR vendors tracekit to alleviate some issues with ESM compatibility.
Currently the typescript conversion is minimal. It adds the types which are largely compatible and leaves most of it reasonably unchanged.
This PR does not port the tests from tracekit to this repository. A subsequent PR will do this.
feat: Vendor TraceKit
feat: Export browser-telemetry initialization method.
Jira: EMSR-14
Jira: EMSR-15
> feat: Vendor TraceKit

- packages/telemetry/browser-telemetry/__tests__/BrowserTelemetryImpl.test.ts
- packages/telemetry/browser-telemetry/__tests__/options.test.ts
- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/api/Options.ts
- packages/telemetry/browser-telemetry/src/collectors/http/fetchDecorator.ts
- packages/telemetry/browser-telemetry/src/options.ts
This PR adds the ability to specify a filter that runs when adding any breadcrumb. The filter can return a modified breadcrumb, or return undefined to filter the breadcrumb entirely.
This could be used to redact any information which a customer doesn't want in a bread crumb.
> feat: Add support for breadcrumb filtering.

- packages/telemetry/browser-telemetry/__tests__/BrowserTelemetryImpl.test.ts
- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
This PR adds an event which is emitted when a session is started.
It also removes some unused code related to session replay.
feat: Add support for the session init event.
chore: Remove session capture until session replay is added.
> feat: Add support for the session init event.

- packages/telemetry/browser-telemetry/__tests__/singleton/singletonInstance.test.ts
- packages/telemetry/browser-telemetry/__tests__/singleton/singletonMethods.test.ts
- packages/telemetry/browser-telemetry/src/index.ts
- packages/telemetry/browser-telemetry/src/singleton/index.ts
- packages/telemetry/browser-telemetry/src/singleton/singletonInstance.ts
- packages/telemetry/browser-telemetry/src/singleton/singletonMethods.ts
This PR adds a singleton interface to the EM SDK to simplify common usage.
You can still create individual browser telemetry instances, but there is a default instance with module level functions for each operation.
Minimal example.
```
import * as LDTelemetry from '@launchdarkly/browser-telemetry`
LDTelemetry.initTelemetry();
LDTelemetry.register(ldClient);
// For manual error capture.
LDTelemetry.captureError(someError);
```
> feat: Add singleton support for browser-telemetry.

- packages/telemetry/browser-telemetry/__tests__/singleton/singletonMethods.test.ts
- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/api/BrowserTelemetry.ts
- packages/telemetry/browser-telemetry/src/api/client/BrowserTelemetryInspector.ts
- packages/telemetry/browser-telemetry/src/inspectors.ts
- packages/telemetry/browser-telemetry/src/singleton/singletonMethods.ts
This is a compatibility improvement PR intended to make the telemetry package less dependent on a specific SDK package.
The inspector interface between 3.x and 4.x has some minor differences and this provides a more broad interface that is compatible with both.
> feat: Make browser-telemetry specific inspector type.

- packages/telemetry/browser-telemetry/__tests__/options.test.ts
- packages/telemetry/browser-telemetry/src/options.ts
There was a mistake in checking the filters option for breadcrumbs. This fixes the issue and ensures the all options parsing doesn't have any warnings logged.
> fix: Fix breadcrumb filter option parsing.

- packages/telemetry/browser-telemetry/__tests__/BrowserTelemetryImpl.test.ts
- packages/telemetry/browser-telemetry/__tests__/options.test.ts
- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/api/Options.ts
- packages/telemetry/browser-telemetry/src/options.ts
This PR adds support for error level filtering. This is the highest level filter type capable of filtering on any data.
Other filters are provided to simplify the implementation of filtering across all error types. Breadcrumb filters could be implemented in terms of an error filter, but they would have higher complexity and different performance characteristics. For example with a breadcrumb filter we filter that breadcrumb regardless of how many events it may appear in, versus having to filter that same breadcrumb each time an event is captures.
Custom url filters operate at the HTTP capture level similarly reducing the frequency of redaction.
> feat: Add the ability to filter errors.

- packages/shared/akamai-edgeworker-sdk/src/featureStore/index.ts
- packages/shared/sdk-server-edge/src/api/EdgeFeatureStore.ts
- packages/shared/sdk-server-edge/src/utils/mockFeatureStore.ts
- packages/shared/sdk-server/__tests__/data_sources/createPayloadListenersFDv2.test.ts
- packages/shared/sdk-server/__tests__/data_sources/createStreamListeners.test.ts
- packages/shared/sdk-server/src/api/subsystems/LDDataSourceUpdates.ts
- packages/shared/sdk-server/src/api/subsystems/LDFeatureStore.ts
- packages/shared/sdk-server/src/data_sources/DataSourceUpdates.ts
- packages/shared/sdk-server/src/options/Configuration.ts
- packages/shared/sdk-server/src/store/InMemoryFeatureStore.ts
- packages/shared/sdk-server/src/store/PersistentDataStoreWrapper.ts
- packages/store/node-server-sdk-dynamodb/src/DynamoDBFeatureStore.ts
- packages/store/node-server-sdk-redis/src/RedisFeatureStore.ts
Splitting these changes up into multiple PRs to keep them manageable and because we can't merge directly to main as `applyChanges` is dependent on transaction support in the PersistentDataStore.
Existing tests are exercising applyChanges, but through init, upsert, and delete.  Plan to add applyChanges tests in ta/fdv2-temporary-holding after transaction support is added to PersistentDataStore in a subsequent PR as part of SDK-1029
> chore: preparation work for FDv2 feature store and persistence support

- .github/workflows/manual-publish-docs.yml
- .github/workflows/manual-publish.yml
- .github/workflows/release-please.yml
- .release-please-manifest.json
- packages/telemetry/browser-telemetry/src/api/Breadcrumb.ts
- packages/telemetry/browser-telemetry/src/api/Options.ts
- packages/telemetry/browser-telemetry/src/api/client/index.ts
- packages/telemetry/browser-telemetry/src/api/index.ts
- packages/telemetry/browser-telemetry/src/index.ts
- packages/telemetry/browser-telemetry/src/singleton/singletonMethods.ts
- release-please-config.json
Add release-please support for browser-telemetry and address a number of minor issues.
chore: Add browser-telemetry to release please.
fix: Export BrowserTelemetry, BrowserTelemetryInspector, and ImplementsCrumb.
chore: Update documentation comment links that were invalid.
feat: Rename initializeTelemetryInstance to initTelemetryInstance for consistency with initTelemetry. 
> chore: Add browser-telemetry to release please.

- packages/telemetry/browser-telemetry/__tests__/BrowserTelemetryImpl.test.ts
- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/api/client/LDClientInitialization.ts
- packages/telemetry/browser-telemetry/src/api/client/index.ts
During initialization the js-client-sdk does some context processing. This is an async operation which will add keys to anonymous contexts. Being as this doesn't happen synchronously within the initialization call there is a possibility that you register the telemetry SDK before that initialization is complete.
This PR updates the registration to attempt to wait for initialization. This is a larger window than we need to wait, but ensures that process will be complete.
> fix: Fix race condition with client registration.

- packages/sdk/react-native/src/platform/locale.ts
This check seems necessary for the new architecture (on React Native 0.77) to prevent an immediate crash.
Closes https://github.com/launchdarkly/js-core/issues/757
> fix(react-native): check for nullability in SettingsManager?.settings

- packages/sdk/server-ai/README.md
https://launchdarkly.atlassian.net/browse/DOCS-1126
Updated README to match current usage (`config` not `modelConfig`)
n/a
Noticed by an LD engineer. Per offline conversation, updating PR title to trigger a release for this, so that our npm page updates as well.
> fix(docs): Node.js AI SDK: modelConfig --> config in readme

- packages/shared/sdk-server/src/store/InMemoryFeatureStore.ts
- packages/shared/sdk-server/src/store/PersistentDataStoreWrapper.ts
- packages/shared/sdk-server/src/store/TransactionalPersistentStore.ts
SDK-1029
Adds TransactionalPersistentStore containing memory store and persistence store.  Swaps on basis being provided as necessary.
Planning to add tests on holding branch (PR target branch).
> feat: adds fdv2 transactional persistent store

- packages/sdk/akamai-edgekv/__tests__/index.test.ts
- packages/sdk/akamai-edgekv/src/index.ts
- packages/sdk/svelte/svelte.config.js
- packages/shared/akamai-edgeworker-sdk/__tests__/featureStore/cacheableStore.test.ts
- packages/shared/akamai-edgeworker-sdk/src/api/LDClient.ts
- packages/shared/akamai-edgeworker-sdk/src/featureStore/cacheableStoreProvider.ts
- packages/shared/akamai-edgeworker-sdk/src/index.ts
When the SDK retrieves data from the EdgeKV, it does so using a single
sub-request per call to `variation`, `variationDetail`, or
`allFlagsState`. The problem is that Akamai imposes a limit of 4
sub-requests per handler event.
If a customer evaluates more than 4 distinct flags during the handling
of a single event, subsequent flag lookups would fail. To combat this,
we now cache the flag values for a specified amount of time.
> feat: Add cacheTtlMs option

- packages/telemetry/browser-telemetry/__tests__/BrowserTelemetryImpl.test.ts
- packages/telemetry/browser-telemetry/__tests__/options.test.ts
- packages/telemetry/browser-telemetry/__tests__/stack/StackParser.test.ts
- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/api/Options.ts
- packages/telemetry/browser-telemetry/src/options.ts
- packages/telemetry/browser-telemetry/src/stack/StackParser.ts
When using browser-telemetry for just metrics it is probably best to disable all breadcrumbs and stack information. This PR makes it simple to do so.
```
initTelemetry({breadcrumbs: false, stack: false});
```
> feat: Option to disable all breadcrumbs and stack.

- .github/ISSUE_TEMPLATE/package-telemetry-browser-telemetry--bug_report.md
- .github/ISSUE_TEMPLATE/package-telemetry-browser-telemetry-feature_request.md
- packages/telemetry/browser-telemetry/README.md
Add issue templates and update the readme.
> chore: Issue template + readme updates.

- packages/shared/sdk-server/__tests__/store/PersistentStoreWrapper.test.ts
- packages/shared/sdk-server/__tests__/store/TransactionalPersistentStore.test.ts
- packages/shared/sdk-server/src/api/subsystems/LDFeatureStore.ts
- packages/shared/sdk-server/src/store/AsyncStoreFacade.ts
- packages/shared/sdk-server/src/store/InMemoryFeatureStore.ts
- packages/shared/sdk-server/src/store/TransactionalPersistentStore.ts
- packages/shared/sdk-server/src/store/index.ts
> chore: adding more FDv2 tests

- packages/sdk/server-ai/__tests__/LDAIConfigTrackerImpl.test.ts
- packages/sdk/server-ai/src/LDAIClientImpl.ts
- packages/sdk/server-ai/src/LDAIConfigTrackerImpl.ts
Added support for versioned metrics for AI Configs
> feat: add support for versioned metrics for AI Configs

- packages/shared/sdk-server/__tests__/LDClientImpl.events.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
> fix: Fix issue where flush callback could be called twice.

- packages/telemetry/browser-telemetry/README.md
- packages/telemetry/browser-telemetry/__tests__/collectors/http/fetch.test.ts
- packages/telemetry/browser-telemetry/__tests__/collectors/http/xhr.test.ts
- packages/telemetry/browser-telemetry/__tests__/filters/defaultUrlFilter.test.ts
- packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts
- packages/telemetry/browser-telemetry/src/collectors/http/HttpCollectorOptions.ts
- packages/telemetry/browser-telemetry/src/collectors/http/fetch.ts
- packages/telemetry/browser-telemetry/src/collectors/http/xhr.ts
- packages/telemetry/browser-telemetry/src/filters/defaultUrlFilter.ts
A URL filter was throwing an exception. This fixes the filter to prevent that exception, but it also makes the fetch/xhr wrappers more resilient to ensure we do not prevent requests from functioning when a filter fails.
> fix: Fix issue processing URLs for fetch and XHR requests.

- packages/sdk/akamai-edgekv/src/index.ts
The pending v2.0.0 release of the Akamai common package handles this
fallback for us, rendering this check redundant.
> chore: Remove redundant default handling

- packages/sdk/server-ai/CHANGELOG.md
- packages/sdk/server-ai/examples/bedrock/README.md
- packages/sdk/server-ai/examples/openai/README.md
- packages/sdk/server-ai/src/api/LDAIClient.ts
- packages/sdk/server-ai/src/api/config/LDAIConfig.ts
- packages/telemetry/browser-telemetry/CHANGELOG.md
https://launchdarkly.atlassian.net/browse/DOCS-2117
Style guide change requires an update in capitalization here.
> docs: AI config --> AI Config name change

- contract-tests/index.js
- packages/sdk/browser/__tests__/BrowserClient.test.ts
- packages/sdk/browser/contract-tests/entity/src/TestHarnessWebSocket.ts
- packages/sdk/browser/contract-tests/suppressions.txt
- packages/shared/common/__tests__/internal/events/EventProcessor.test.ts
- packages/shared/common/src/internal/events/EventProcessor.ts
- packages/shared/common/src/internal/events/InputMigrationEvent.ts
- packages/shared/sdk-server/__tests__/MigrationOpEventConversion.test.ts
- packages/shared/sdk-server/__tests__/MigrationOpTracker.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/MigrationOpEventConversion.ts
- packages/shared/sdk-server/src/MigrationOpTracker.ts
- packages/shared/sdk-server/src/api/data/LDMigrationOpEvent.ts
- Support inlining context for custom events.  The logic for this needs to happen in EventProcessor which is shared between server and client sdks in js-core.  It has been verified with product analytics that this is ok for the client sdks.
- Support inlining context for migration events.  This causes a change in the public interface for `LDClient.trackMigration` where the `LDMigrationOpEvent` parameter has been modified.  `contextKeys` has been made optional and deprecated in favor of `context` and all internal uses of `LDMigrationOpEvent` have been changed to use `context`.
feat: Support inline context for custom and migration events
fix: Deprecate LDMigrationOpEvent.contextKeys in favor of …
> feat: Support inline context for custom and migration events

- CONTRIBUTING.md
Add notes on repo organization and dependencies.
This PR is best reviewed with the rich diff
> chore: Add repo organization to CONTRIBUTING.md

- contract-tests/index.js
- contract-tests/sdkClientEntity.js
- packages/sdk/server-node/__tests__/platform/NodeRequests.test.ts
- packages/sdk/server-node/src/platform/NodePlatform.ts
- packages/sdk/server-node/src/platform/NodeRequests.ts
- packages/shared/common/__tests__/internal/events/EventSender.test.ts
- packages/shared/common/src/api/platform/Requests.ts
- packages/shared/common/src/internal/events/EventSender.ts
- packages/shared/sdk-server/src/api/options/LDOptions.ts
- packages/shared/sdk-server/src/options/Configuration.ts
- packages/shared/sdk-server/src/options/ValidatedOptions.ts
LDConfig option `enableEventCompression` was added for js-server-sdk-common and NodeRequests was modified to support gzip compression of POST bodies if this option is enabled.
> feat: Option to use gzip to compress event

- CONTRIBUTING.md
Add some additional build information to the contributing documentation.
> chore: Add build instructions for single projects.

- packages/sdk/browser/__tests__/options.test.ts
- packages/sdk/browser/src/BrowserClient.ts
- packages/sdk/browser/src/options.ts
The browser SDK was incorrectly handling its default flush interval configuration.
There are two layers to defaults for the browser SDK. The first is defaults which differ from the base configuration defaults, second is defaults for browser specific configuration.
The base defaults were being applied to the browser specific configuration, which meant those changes were being lost and instead the base default was being used instead.
Fixes: SDK-1199
> fix: Handle default flush interval for browser SDK.

- packages/sdk/server-node/package.json
- packages/shared/common/__tests__/internal/metadata/InitMetadata.test.ts
- packages/shared/common/src/api/platform/EventSource.ts
- packages/shared/common/src/internal/index.ts
- packages/shared/common/src/internal/metadata/InitMetadata.ts
- packages/shared/common/src/internal/metadata/index.ts
- packages/shared/sdk-server/__tests__/data_sources/DataSourceUpdates.test.ts
- packages/shared/sdk-server/__tests__/data_sources/PollingProcessor.test.ts
- packages/shared/sdk-server/__tests__/data_sources/Requestor.test.ts
- packages/shared/sdk-server/__tests__/data_sources/StreamingProcessor.test.ts
- packages/shared/sdk-server/__tests__/data_sources/createStreamListeners.test.ts
- packages/shared/sdk-server/__tests__/hooks/HookRunner.test.ts
- packages/shared/sdk-server/__tests__/store/InMemoryFeatureStore.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/api/integrations/Hook.ts
- packages/shared/sdk-server/src/api/subsystems/LDDataSourceUpdates.ts
- packages/shared/sdk-server/src/api/subsystems/LDFeatureRequestor.ts
- packages/shared/sdk-server/src/api/subsystems/LDFeatureStore.ts
- packages/shared/sdk-server/src/data_sources/DataSourceUpdates.ts
- packages/shared/sdk-server/src/data_sources/PollingProcessor.ts
- packages/shared/sdk-server/src/data_sources/Requestor.ts
- packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
- packages/shared/sdk-server/src/data_sources/createStreamListeners.ts
- packages/shared/sdk-server/src/hooks/HookRunner.ts
- packages/shared/sdk-server/src/store/AsyncStoreFacade.ts
- packages/shared/sdk-server/src/store/InMemoryFeatureStore.ts
- packages/telemetry/node-server-sdk-otel/__tests__/TracingHook.test.ts
- packages/telemetry/node-server-sdk-otel/src/TracingHook.ts
If present, `environmentId` is now passed to the HookRunner in the evaluation series.
For streaming connections:
- Response headers are now attached to the `open` event (https://github.com/launchdarkly/js-eventsource/pull/33)
- `StreamingProcessor` passes these headers to the stream listeners via `processJson`.  The listener for the PUT event extracts the `environmentId` from the headers and passes this as initialization metadata to the underlying feature store.
For polling connections:
- `PollingProcessor` retrieves  the response headers via the underlying `Requestor` and extracts the `environmentId` from the headers and passes this as initialization metadata to the underlying feature store.
LDClient will then call …
> feat: Environment ID support for hooks

- packages/shared/common/__tests__/datasource/dataSourceList.test.ts
- packages/shared/common/__tests__/subsystem/DataSystem/CompositeDataSource.test.ts
- packages/shared/common/src/api/subsystem/DataSystem/DataSource.ts
- packages/shared/common/src/api/subsystem/DataSystem/index.ts
- packages/shared/common/src/api/subsystem/index.ts
- packages/shared/common/src/datasource/CompositeDataSource.ts
- packages/shared/common/src/datasource/dataSourceList.ts
- packages/shared/sdk-server/__tests__/data_sources/OneShotInitializerFDv2.test.ts
- packages/shared/sdk-server/__tests__/data_sources/PollingProcessorFDv2.test.ts
- packages/shared/sdk-server/__tests__/data_sources/StreamingProcessorFDv2.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/data_sources/OneShotInitializerFDv2.ts
- packages/shared/sdk-server/src/data_sources/PollingProcessorFDv2.ts
- packages/shared/sdk-server/src/data_sources/StreamingProcessorFDv2.ts
> feat: CompositeDataSource blacklists DataSources that report unrecoverable error

- package.json
- packages/sdk/browser/contract-tests/entity/src/ClientEntity.ts
- packages/sdk/browser/contract-tests/entity/src/TestHarnessWebSocket.ts
- packages/sdk/browser/contract-tests/entity/src/TestHook.ts
- packages/sdk/browser/src/common.ts
- packages/shared/sdk-client/src/index.ts
Adds hook support in browser contract tests as well as adding the `track-hooks` capability.
> chore: Add hook support in browser contract tests

- package.json
- packages/sdk/server-node/__tests__/LDClientNode.proxy.test.ts
- packages/sdk/server-node/__tests__/LDClientNode.tls.test.ts
- packages/sdk/server-node/package.json
- packages/shared/common/__tests__/internal/fdv2/PayloadStreamReader.test.ts
- packages/shared/common/__tests__/options/ServiceEndpoints.test.ts
- packages/shared/common/__tests__/subsystem/DataSystem/CompositeDataSource.test.ts
- packages/shared/common/src/api/platform/EventSource.ts
- packages/shared/common/src/api/platform/Requests.ts
- packages/shared/common/src/datasource/CompositeDataSource.ts
- packages/shared/common/src/datasource/errors.ts
- packages/shared/common/src/datasource/index.ts
- packages/shared/common/src/index.ts
- packages/shared/common/src/internal/fdv2/payloadProcessor.ts
- packages/shared/common/src/internal/fdv2/proto.ts
- packages/shared/sdk-server/__tests__/data_sources/OneShotInitializerFDv2.test.ts
- packages/shared/sdk-server/__tests__/data_sources/PollingProcessorFDv2.test.ts
- packages/shared/sdk-server/__tests__/data_sources/Requestor.test.ts
- packages/shared/sdk-server/__tests__/data_sources/StreamingProcessor.test.ts
- packages/shared/sdk-server/__tests__/data_sources/StreamingProcessorFDv2.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/data_sources/PollingProcessorFDv2.ts
- packages/shared/sdk-server/src/data_sources/Requestor.ts
- packages/shared/sdk-server/src/data_sources/StreamingProcessorFDv2.ts
- packages/shared/sdk-server/src/options/Configuration.ts
Will validate on holding branch later.
SDK-1179
Adds FDv1 fallback error type.  FDv2 datasources now report that error type if they see the fallback header from the FDv2 endpoints.
Updates FDv2 polling datasource to support being constructed in a FDv1 to FDv2 conversion mode.  In that mode, the response from an FDv1 endpoint will be converted to an FDv2 payload and passed through the FDv2 payloadProcessor.
CompositeDataSource now supports an FDv1 fallback synchronizer list.  If any datasource reports the FDv1 fallback error, the CompositeDataSource switches to use the fallback synchronizer list.
This PR also contains tweaks to get the holding branch working with the latest contract tests that got some tweaks …
> feat: falls back to FDv1 polling if flag delivery sends fallback header

- packages/sdk/browser/__tests__/BrowserDataManager.test.ts
- packages/sdk/browser/__tests__/platform/BrowserInfo.test.ts
- packages/sdk/browser/src/BrowserClient.ts
- packages/sdk/browser/src/platform/BrowserInfo.ts
- packages/sdk/browser/src/platform/BrowserPlatform.ts
- packages/sdk/react-native/__tests__/MobileDataManager.test.ts
- packages/sdk/react-native/__tests__/ReactNativeLDClient.test.ts
- packages/sdk/react-native/src/ReactNativeLDClient.ts
- packages/sdk/react-native/src/platform/PlatformInfo.ts
- packages/sdk/react-native/src/platform/index.ts
Wrappers are accessed through the platform, but react-native and the browser implementation were not propagating these to the platform.
The first implementation was the node platform, which handled this correctly. The Cloudlare and RN platform didn't, and then the RN platform was used as reference for implementing the browser platform.
So, this also affects edge and a similar update should be considered for those SDKs.
> fix: Client SDKs should use wrapper information.

- packages/shared/common/__tests__/logging/format.test.ts
There was a minor change to the logging output in node 22 for object string conversion. This makes a test more lenient to account for it.
> chore: Fix unit tests to work with node 22.

- .github/workflows/server-node.yml
The rennovate PR adjusts all the builds which just use node as a tool, but server-node is using a range of versions for validation. This updates the versions to be 18 and 22 instead of 18 and 21.
> chore: Replace node 21 with 22 for server-node CI.

- packages/shared/sdk-client/__tests__/async/AsyncTaskQueue.test.ts
- packages/shared/sdk-client/src/async/AsyncTaskQueue.ts
This PR adds an async task queue. This queue is roughly based on the flutter implementation, but with support for non-shedable tasks like iOS.
https://github.com/launchdarkly/flutter-client-sdk/blob/01841d65d8eb9dbf7cdc1c29b76f2ac8a699fb05/packages/common/lib/src/async/async_single_queue.dart
https://github.com/launchdarkly/ios-client-sdk/blob/082430ff008d76d503327c52b27e3b2af99c3ef2/LaunchDarkly/LaunchDarkly/ServiceObjects/SheddingQueue.swift
This is a `chore`, because the type is unused and doesn't need a release. A subsequent PR will use it for functionality.
This queue is going to be used for an implementation of the client-side identify spec.
https://github.com/launchdarkly/sdk-specs/tree/main/specs/CSI-client-side-identify
(Spec is private.)
Available for review by anyone, I added …
> chore: Add implementation for async task queue.

- packages/shared/akamai-edgeworker-sdk/src/featureStore/index.ts
- packages/shared/common/src/api/subsystem/DataSystem/DataSource.ts
- packages/shared/common/src/datasource/CompositeDataSource.ts
- packages/shared/common/src/options/ServiceEndpoints.ts
- packages/shared/sdk-server-edge/src/api/EdgeFeatureStore.ts
- packages/shared/sdk-server/__tests__/data_sources/PollingProcessorFDv2.test.ts
- packages/shared/sdk-server/__tests__/data_sources/Requestor.test.ts
- packages/shared/sdk-server/__tests__/data_sources/createPayloadListenersFDv2.test.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/api/subsystems/LDDataSourceUpdates.ts
- packages/shared/sdk-server/src/api/subsystems/LDFeatureRequestor.ts
- packages/shared/sdk-server/src/api/subsystems/LDFeatureStore.ts
- packages/shared/sdk-server/src/data_sources/DataSourceUpdates.ts
- packages/shared/sdk-server/src/data_sources/PollingProcessorFDv2.ts
- packages/shared/sdk-server/src/data_sources/Requestor.ts
- packages/shared/sdk-server/src/data_sources/createPayloadListenerFDv2.ts
- packages/shared/sdk-server/src/store/AsyncStoreFacade.ts
- packages/shared/sdk-server/src/store/InMemoryFeatureStore.ts
- packages/shared/sdk-server/src/store/PersistentDataStoreWrapper.ts
- packages/shared/sdk-server/src/store/TransactionalPersistentStore.ts
Will be done on target branch in the future as part of integration testing.
SDK-1044
Pipes selector through datasource and feature store layers / APIs.  InMemoryFeatureStore holds the selector in memory at runtime.  When datasources need the selector for making their requests, they invoke a selectorGetter lambda that is hooked up to the InMemoryFeatureStore.
> feat: now utilizes FDv2 basis param for more efficient polling

- packages/shared/sdk-client/src/api/integrations/Hooks.ts
Found during https://launchdarkly.atlassian.net/browse/DOCS-2295, https://github.com/launchdarkly/ld-docs-private/pull/5935
The `beforeIdentify` and `afterIdentify` methods in the `Hook` interface had identical documentation about when they're called, which is not how they actually behave.
> chore(docs): afterIdentify occurs at a different time than beforeIdentify

- packages/sdk/react-native/__tests__/MobileDataManager.test.ts
- packages/sdk/react-native/src/MobileDataManager.ts
https://github.com/launchdarkly/js-core/issues/868
Provides Requestor configuration in correct order.
None.
Fixes https://github.com/launchdarkly/js-core/issues/868
Edit: in functions with many arguments, consider arguments with an object, so that it's more clear what values are assigned to which keys.
> fix: Requestor initialized with wrong withReasons and useReport config

- .github/ISSUE_TEMPLATE/package-sdk-combined-browser--bug_report.md
- .github/ISSUE_TEMPLATE/package-sdk-combined-browser--feature_request.md
- .github/workflows/combined-browser.yml
- .github/workflows/manual-publish-docs.yml
- .github/workflows/manual-publish.yml
- .github/workflows/release-please.yml
- .release-please-manifest.json
- README.md
- package.json
- packages/sdk/combined-browser/LICENSE
- packages/sdk/combined-browser/README.md
- packages/sdk/combined-browser/__tests__/index.test.ts
- packages/sdk/combined-browser/jest.config.json
- packages/sdk/combined-browser/package.json
- packages/sdk/combined-browser/setup-jest.js
- packages/sdk/combined-browser/src/index.ts
- packages/sdk/combined-browser/tsconfig.eslint.json
- packages/sdk/combined-browser/tsconfig.json
- packages/sdk/combined-browser/tsconfig.ref.json
- packages/sdk/combined-browser/tsconfig.test.json
- packages/sdk/combined-browser/tsup.config.ts
- packages/sdk/combined-browser/typedoc.json
- release-please-config.json
- tsconfig.json
Scaffolds the combined browser package. This is a package with pre-configured observability.
> chore: Add combined browser package.

- packages/sdk/server-node/__tests__/LDClientNode.plugin.test.ts
- packages/sdk/server-node/src/LDClientNode.ts
- packages/sdk/server-node/src/api/LDOptions.ts
- packages/sdk/server-node/src/api/LDPlugin.ts
- packages/sdk/server-node/src/index.ts
- packages/shared/sdk-server/src/LDClientImpl.ts
- packages/shared/sdk-server/src/createPluginEnvironmentMetadata.ts
- packages/shared/sdk-server/src/options/Configuration.ts
- packages/shared/sdk-server/src/options/ServerInternalOptions.ts
This adds plugin support for the node server SDK.
Plugin support is leaf-SDK specific because plugins use the interface of the SDK. The interface of the SDK has slightly different capabilities based on implementation.
Unfortunately this isn't a simple problem to tackle with regards to organization. We could use composition with the common functionality being generic over the SDK interface. Doing so would require some breaking changes to all the SDK implementation, but could be worth it in the future.
For not though we have to settle for some complexity with the plugin interface being defined per-sdk and the call to the initialization code being per-sdk.
This was able to re-use the generic types and functions which means this isn't very much code.
This SDK had another complexity which is …
> feat: Add plugin support for node.

- packages/sdk/server-node/package.json
- packages/sdk/server-node/src/platform/NodeRequests.ts
See https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/CHANGELOG.md#600
> chore: upgrade https-proxy-agent to 7.x

- packages/shared/common/src/api/subsystem/DataSystem/CallbackHandler.ts
- packages/shared/common/src/datasource/CompositeDataSource.ts
This PR is nearly an empty commit and removes a completed TODO with a `feat` commit to trigger a release.
Up to this point, no FDv2 changes in shared/common had been made in a `feat` commit, so`js-sdk-common` didn't have a release triggered since May 21st.  This was overlooked as additional functionality was merged into main in other packages that did get released.
> feat: additional FDv2 functionality

- package.json
This PR pins @types/node at 24.1.0 in order to fix CI check failures
24.3.0 is causing errors such as:
```
../../../node_modules/@types/node/child_process.d.ts(309,9): error TS1165: A computed property name in an ambient context must refer to an expression whose type is a literal type or a 'unique symbol' type.
```
> chore: pin @types/node to fix CI check failures
