launchdarkly/js-core

contributing/initial-package-publish.md, release-please-config.json
Releasing 0.0.1 versions of the cloudflare and edge common packages for testing.
=> chore: add cloudflare and sdk-server-edge to release please

.github/workflows/manual-publish-docs.yml, .github/workflows/manual-publish.yml, .github/workflows/release-please.yml
This adds the cloudflare and sdk-server-edge packages to the publish and release-please ga's.
=> feat: add cloudflare and sdk-server-edge to publish scripts

scripts/publish-doc.sh
=> chore: Have the doc publish script configure pulls to merge.

packages/sdk/cloudflare/README.md, packages/sdk/cloudflare/example/src/index.ts, packages/shared/sdk-server-edge/src/utils/validateOptions.ts
The readme instructions were sparse and incorrect.
=> chore: improve readme instructions

.github/workflows/release-please.yml, release-please-config.json
Fixing whitespace in yaml config and a typo
=> chore: fix yaml whitespace

packages/sdk/cloudflare/README.md
The README has outdated information from v1 and needs to be updated.
=> chore: improve readme

packages/sdk/cloudflare/package.json, packages/sdk/server-node/package.json, packages/sdk/vercel/package.json, packages/shared/common/package.json, packages/shared/sdk-server-edge/package.json, packages/shared/sdk-server/package.json, release-please-config.json
Initial major release for common packages and cloudflare.
=> feat: initial major release

.github/ISSUE_TEMPLATE/package-sdk-cloudflare--bug_report.md, .github/ISSUE_TEMPLATE/package-sdk-cloudflare--feature_request.md, .github/ISSUE_TEMPLATE/package-sdk-vercel--bug_report.md, .github/ISSUE_TEMPLATE/package-sdk-vercel--feature_request.md, .github/ISSUE_TEMPLATE/package-shared-sdk-server-edge--bug_report.md, .github/ISSUE_TEMPLATE/package-shared-sdk-server-edge--feature_request.md
=> chore: Add issue templates for edge SDKs.

.github/workflows/akamai.yml, .github/workflows/manual-publish-docs.yml, .github/workflows/manual-publish.yml, .github/workflows/release-please.yml, README.md, package.json, packages/sdk/akamai/CHANGELOG.md, packages/sdk/akamai/LICENSE, packages/sdk/akamai/README.md, packages/sdk/akamai/jest.config.json, packages/sdk/akamai/package.json, packages/sdk/akamai/src/index.test.ts, packages/sdk/akamai/src/index.ts, packages/sdk/akamai/tsconfig.eslint.json, packages/sdk/akamai/tsconfig.json, packages/sdk/akamai/tsconfig.ref.json, release-please-config.json, tsconfig.json
Setting up the basic structure for the Akamai SDK.
- Created basic test
- Created basic init function that returns Hello World
- Modeled structure after the Cloudflare directory
=> feat: Adding akamai SDK

packages/sdk/akamai/src/libs/edgekv.js, packages/sdk/akamai/tsconfig.json
Added Akamai's edgekv helper function
=> feat: Added EdgeKV helper lib

packages/sdk/akamai/src/edgeKVProvider.ts
Added Edge KV store provider for Akamai
=> feat: Added Akamai Edge store provider

packages/sdk/vercel/src/createPlatformInfo.ts
Doing this as a chore to prevent an addition release version.
=> chore: Update platform version.

release-please-config.json
Release beta versions for the Akamai SDKs
- Akamai Base
- Akamai EdgeKV
- Akamai Edgeworker
=> feat: Release beta version of Akamai SDKs

release-please-config.json
Releasing latest version of Akamai SDKs
=> chore: Release Akamai SDKs

release-please-config.json
Reverts launchdarkly/js-core#165
=> chore: Revert Release Akamai SDKs

.github/workflows/manual-publish.yml, .github/workflows/release-please.yml, release-please-config.json
chore: Run Redis/Dynamo during releases to allow redis/dynamo tests to pass.
=> chore: Remove release-as for redis/dynamo.

.github/workflows/manual-publish-docs.yml
Needed these for manual docs as well.
=> chore: Add Redis/Dynamo for doc publish steps as well.

packages/sdk/server-node/README.md, packages/store/node-server-sdk-dynamodb/README.md, packages/store/node-server-sdk-redis/README.md, release-please-config.json
This prepares to do the Node.js server major release as well as the release of the redis and dynamodb integrations.
=> feat: Node server SDK major release.

packages/sdk/akamai-base/README.md, packages/sdk/akamai-base/example/package.json, packages/sdk/akamai-edgekv/README.md, packages/sdk/akamai-edgekv/example/package.json, release-please-config.json
Preparing to GA the Akamai SDKs
=> feat: Release v1.0.0 of Akamai SDKs

release-please-config.json
Cleaned up release-please-config after v1.0.0 release.
=> chore: Cleaning up after releasing v1.0.0

packages/shared/common/__tests__/internal/events/EventSummarizer.test.ts, packages/shared/common/package.json, packages/shared/common/src/internal/events/EventSummarizer.ts, packages/shared/common/src/internal/events/InputEvalEvent.ts, packages/shared/sdk-server/src/evaluation/data/Flag.ts, packages/shared/sdk-server/src/events/EventFactory.ts
feat: Add `sampleWeight` to flag data model.
=> feat: Add support for exclude from summaries.

package.json, packages/sdk/akamai-base/example/package.json, packages/sdk/akamai-base/example/tsconfig.json, packages/sdk/akamai-base/package.json, packages/sdk/akamai-base/tsconfig.json, packages/sdk/akamai-edgekv/example/package.json, packages/sdk/akamai-edgekv/package.json, packages/sdk/cloudflare/example/package.json, packages/sdk/cloudflare/package.json, packages/sdk/server-node/package.json, packages/sdk/vercel/examples/complete/package.json, packages/sdk/vercel/examples/route-handler/package.json, packages/sdk/vercel/package.json, packages/shared/akamai-edgeworker-sdk/package.json, packages/shared/common/package.json, packages/shared/sdk-server-edge/package.json, packages/shared/sdk-server/package.json, packages/store/node-server-sdk-dynamodb/package.json, packages/store/node-server-sdk-redis/package.json
=> chore: Update typedoc version. Pin typescript.

contract-tests/index.js
We did some refactoring of the contact tests to allow for Java/Ruby to implement a subset of event sampling. That involved adding a couple new categories gated on event sampling. This just adds those capabilities.
=> chore: Use new granular categories for event sampling.

packages/shared/sdk-server/__tests__/LDClientImpl.test.ts, packages/shared/sdk-server/src/LDClientImpl.ts
=> fix: Better handle waiting for initialization for failure cases.

packages/sdk/vercel/README.md, release-please-config.json
Preview: https://github.com/launchdarkly/js-core/blob/dd737f0db559f764b0b6344182549a0f8d487a30/packages/sdk/vercel/README.md
=> feat: Support analytics events in the vercel SDK.

.github/workflows/manual-publish.yml
adding sdk-client and rn repos to rp
=> chore: adding sdk-client and rn repos to rp

packages/sdk/react-native/example/app.json, packages/sdk/react-native/jest.config.json, packages/sdk/react-native/jest.config.ts, packages/sdk/react-native/package.json, packages/sdk/react-native/src/ReactNativeLDClient.test.ts, packages/sdk/react-native/src/provider/LDProvider.test.tsx, packages/sdk/react-native/src/provider/LDProvider.tsx, packages/sdk/react-native/src/provider/reactContext.ts, packages/sdk/react-native/src/provider/setupListeners.test.ts, packages/sdk/react-native/tsconfig.json, packages/sdk/react-native/tsconfig.test.json, release-please-config.json
* Added more coverage for rn sdk.
* Added separate tsconfig.json for tests.
* Improved jest config.
* Removed release-as from release please config.
=> fix: Add more rn sdk unit tests.

packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.test.ts, packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
This should fix #405 or at least provide more logging to debug the issue further if it persists.
=> fix: Stream retry failure due to previous open connection.

.github/workflows/release-please.yml
Mostly ripped from the C++ [PR](https://github.com/launchdarkly/cpp-sdks/commit/eb3e62dd04814168a4787b62508cc8a73c3648cf).
=> chore: Update to release-please v4.

scripts/publish-jsr.sh
I ran and tested this locally now and I am very confident this should work!
=> fix: Remove erroneous jsr.json check.

packages/telemetry/browser-telemetry/__tests__/StackParser.test.ts, packages/telemetry/browser-telemetry/package.json, packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts, packages/telemetry/browser-telemetry/src/stack/StackFrame.ts, packages/telemetry/browser-telemetry/src/stack/StackParser.ts, packages/telemetry/browser-telemetry/src/stack/StackTrace.ts
This is prototype code targeting a prototype feature branch.
This PR adds code for processing stack traces into a uniform shape.
For productionizing the TraceKit code would need vendored and some updated made.
=> feat: Add stack trace processing.

packages/telemetry/browser-telemetry/src/BrowserTelemetryImpl.ts, packages/telemetry/browser-telemetry/src/api/Breadcrumb.ts, packages/telemetry/browser-telemetry/src/collectors/click.ts
Prototype code for prototype feature branch.
=> feat: Add new breadcrumb format.

packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.test.ts, packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
The event source was treating the initial connection as a re-connection. This results in confusing messaging.
This also changes the retrying event, which we do not expose.
When we convert our polyfill to typescript we should use it instead and allow passing a connection method. The reason this is being used is theoretically an issue with fetch not streaming in RN, so it uses an XHR instead.
=> fix: Make it more clear what is happening when an event source is connecting.

contract-tests/index.js, contract-tests/sdkClientEntity.js, packages/sdk/server-node/__tests__/platform/NodeInfo.test.ts, packages/sdk/server-node/src/platform/NodeInfo.ts, packages/sdk/server-node/src/platform/NodePlatform.ts
For contract test implementation see: https://github.com/launchdarkly/sdk-test-harness/pull/223
=> feat: Add wrapper support.

packages/sdk/react-native/example/src/welcome.tsx, packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
Also the buttons had gotten too tall, so I re-arranged them.
=> fix: Handle non-status code errors for streaming connection.

packages/sdk/server-node/src/Emits.ts
Reverts launchdarkly/js-core#646
=> chore:  Revert - Fix incompatibility with @types/node release.

.github/workflows/react-native-detox.yml
Reverts launchdarkly/js-core#623
=> chore: Revert "chore(deps): update reactivecircus/android-emulator-runner digest to c77bfe7"

packages/sdk/server-node/src/platform/NodeRequests.ts
=> fix: Fix typo in proxy-authorization header for basic authentication.

packages/telemetry/browser-telemetry/package.json
=> chore: Remove rrweb dependency.

.github/workflows/react-native-detox.yml
This build does not yet work on ubuntu 24.04.
=> chore: Pin ubuntu version for react native example build.

packages/sdk/fastly/package.json
https://launchdarkly.atlassian.net/browse/DOCS-973
package.json `description` field for Fastly is incorrect, this PR updates it
n/a
I'm not sure what, if anything, needs to happen after this update (is a patch release required for this to get picked up anywhere?)
=> docs: update Fastly package.json description

CONTRIBUTING.md
Start adding some development guidelines to the contributing doc.
=> chore: Start implementing development guidelines.

packages/shared/sdk-server/__tests__/data_sources/StreamingProcessorFDv2.test.ts, packages/shared/sdk-server/src/data_sources/StreamingProcessorFDv2.ts
=> feat: now utilizes FDv2 basis param for streaming

packages/sdk/react-native/example/package.json, packages/sdk/react-native/package.json
https://github.com/launchdarkly/js-core/issues/929
=> feat: Update react native async local storage to v2.
